[programs.localnet]
blog = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet =  "/home/sohom/.config/solana/id.json "

[scripts]
test = "npx mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
